version: "3"
services:
  hub:
    image: seleniarm/hub:4.10
    ports:
      - 4444:4444
      - 4442:4442
      - 4443-4443
  chrome:
    image: seleniarm/node-chromium:4.10
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 4
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
  firefox:
    image: seleniarm/node-firefox:4.10
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 4
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
  selenium-grid:
    image: selenium/docker01
    shm_size: '2g'
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - TEST_SUITE=src/main/resources/test-suites/TestNGSelenium.xml
    volumes:
      - ./output/seleniumGrid:/home/selenium-docker/test-output